[PATCH] CMakeLists.txt: add flag to also compile with GCC 4.7.2
Compiling the examples with GCC 4.7.2 fails with:

  error: 'sleep_for' is not a member of 'std::this_thread'

General hints on the Internet [1, 2] explain the issue with
GCC 4.7.2. Hence, this commit adds the specific _GLIBCXX_USE_NANOSLEEP
definition that makes the compilation with GCC 4.7.2 possible.

[1]
http://stackoverflow.com/questions/12523122/what-is-glibcxx-use-nanosleep-all-about
[2]
http://stackoverflow.com/questions/4438084/stdthis-threadsleep-for-and-gcc

Signed-off-by: Lukas Bulwahn, BMW Car IT GmbH <Lukas.Bulwahn@bmw.de>