test/common/CMakeLists.txt: add missing link with dlt (#602)
The libvsomeip_utilities library uses functions e.g.
dlt_check_library_version/dlt_register_app/dlt_unregister_app which are
provided by dlt therefore add it to linker flags.

Fixes:
x86_64-poky-linux-ld.lld: error: undefined reference due to --no-allow-shlib-undefined: dlt_check_library_version
>>> referenced by test/common/libvsomeip_utilities.so

x86_64-poky-linux-ld.lld: error: undefined reference due to --no-allow-shlib-undefined: dlt_register_app
>>> referenced by test/common/libvsomeip_utilities.so

x86_64-poky-linux-ld.lld: error: undefined reference due to --no-allow-shlib-undefined: dlt_unregister_app
>>> referenced by test/common/libvsomeip_utilities.so

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>