Add missing include for unordered_map
Add missing #include <unordered_map>
Remove unused internal.hpp

Android build is complaining,
local_server.hpp:187:10: error: no template named 'unordered_map' in namespace 'std'; did you mean 'unordered_set'?
And the missing internal.hpp on Android side.